plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.142'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    // 包含数据生成器生成的资源。
    srcDir('src/generated/resources')

    // 从最终输出中排除仅用于开发的资源。
    exclude("**/*.bbmodel") // BlockBench 项目文件

    exclude("src/generated/**/.cache") // 数据生成缓存文件
}

repositories {
}

base {
    archivesName = mod_id
}

// Minecraft 1.21.1 面向用户使用 Java 21，因此 Mod 应以 Java 21 为目标版本。
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    // 指定要使用的 NeoForge 版本。
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
}

// 将 mods.toml 模板中的 ${} 属性展开到构建输出。
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Java 编译使用 UTF-8 字符集。
}

// IDEA 不再自动下载依赖的源码和 Javadoc JAR，因此需要显式启用此行为。
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
