# 设置 Gradle 命令默认使用的内存，可通过用户配置或命令行参数覆盖。
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment 参数名称和 Javadoc 配置说明：
# https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# Parchment 可用版本列表：
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17


# 环境属性

# 可用版本列表：
# https://projects.neoforged.net/neoforged/neoforge
# Minecraft 版本必须与 NeoForge 版本匹配，才能获取有效的构建工件。
minecraft_version=1.21.1

# Minecraft 版本范围可以使用任意正式发布版本作为边界。
# Snapshot、预发布版和候选发布版不保证能够正确排序，因为它们不遵循标准版本排序规则。
minecraft_version_range=[1.21.1]

# NeoForge 版本必须与 Minecraft 版本匹配。
neo_version=21.1.244

# Loader 版本范围只能使用 FML 的主版本号作为边界。
loader_version_range=[1,)


## Mod 属性

# Mod 的唯一标识符必须使用小写英文，并符合正则 [a-z][a-z0-9_]{1,63}。
# 它必须与带有 @Mod 注解的主 Mod 类中的字符串常量一致。
mod_id=bosschongsheng

# Mod 面向玩家显示的可读名称。
mod_name=Boss重生

# Mod 使用的许可证。可参考 https://choosealicense.com/。
mod_license=MIT

# Mod 版本号。可参考 https://semver.org/。
mod_version=1.0.0

# Mod 的 group ID，与 Mod 源码使用的基础 Java 包名一致。
mod_group_id=com.bosschongsheng
